### ISSUE TITLE
Font format

### ISSUE THREAD

**Issue by cabana-banana** [boy1dr/3DWriter#13]
Hi! Great Project!
We are experimenting a lot with old pen plotters, which were made for this purpose. For them we try to build own single stroke fonts, which we would like to test with 3DWriter but the fileformat cmf seems quite exotic. Do you have any information on how the included font files were generated?
thanks and all the best,
Felix

**Comment by boy1dr** [comment]
Hi there, sounds like a fun project :)

The cmf file is a reformatted font file from a set called the Hershey fonts.
They are made for pen plotters but for my purposes I needed to remix the data to be more easily consumed by my program.

Hope that helps

Cheers,
Chris

Sent from my mobile thingy

________________________________
