### ISSUE TITLE
To big spacing on slanted letters

### ISSUE THREAD

**Issue by Lightdm** [boy1dr/3DWriter#17]
When you uses Fonts like "scriptc" there is quite a big gap between a capital "W" and the next letter.

**Comment by boy1dr** [comment]
This is problem that i hope will become clear when i get the font editor up and running.
There is a negative left offset in the original hershey font set that doesn't appear to line up with anything, so instead i just halve the widths and set the spacing based on that and it seems to align much better than using the negative offset.
