### ISSUE TITLE
Can not write the words â ă á ....

### ISSUE THREAD

**Issue by nguyennhattam268** [boy1dr/3DWriter#22]
Help me write the words â á ơ ...

**Comment by boy1dr** [comment]
3DWriter can only write a preset amount of characters, it does not use a "font".
For a complete set of characters available please see http://paulbourke.net/dataformats/hershey/
It is possible that in the future there will be font editor capability in 3DWriter but i have not found the time to add it yet.

**Comment by nguyennhattam268** [comment]
Thank you very much. I want to develop it to get what I want and want it to add an image to gcode tab too. Please help me with the solution.

**Comment by boy1dr** [comment]
I think maybe you use case is a little outside of what 3DWriter can do right now.
Have you looked at inkscape for doing this? it is a little more complicated but it will do what you are looking for.
https://www.evilmadscientist.com/2011/hershey-text-an-inkscape-extension-for-engraving-fonts/

**Comment by nguyennhattam268** [comment]
Thanks. I have used inkscape but still haven't achieved what I want
