### ISSUE TITLE
"Hardware Setup" Menu on 3dwriter.io

### ISSUE THREAD

**Issue by pietropelizzari** [boy1dr/3DWriter#24]
Having made an online version is AMAZING. Though, at the risk of sounding like a complete idiot, I want to report that it took me 3 days to figure out that on the online version you have to click on "Hardware Setup" to actually access the 3d printer options. I would suggest either making it open by default or making it look like a clickable button. Before figuring out that it was a clickable text, I simply thought that you had discontinued the 3D printer options on the online version.

Thanks for this project!

**Comment by boy1dr** [comment]
Thanks for the kind words and the suggestion. It has been updated. Thanks :)
