### ISSUE TITLE
which 3DPrinter do you recommend?

### ISSUE THREAD

**Issue by ChuangLee** [boy1dr/3DWriter#4]
Hi, boy1dr.
Which 3DPrinter did you use for 3DWriter? and is there better choies?

**Comment by boy1dr** [comment]
I just have a basic kit i3 printer i bought off eBay for $250. any printer would be fine as long as you don't mind strapping a pen to it somehow.

**Comment by ChuangLee** [comment]
I wish the machine could use writing brush  for writing, thats means the value of z axis should change autonomously when writting, is it possible? 
like this 
[http://www.yac8.com/upFiles/yac801/2014070479260985.jpg](url)

**Comment by boy1dr** [comment]
If you mount your pen/brush at 45 degree angle instead of straight up and down that should give you the effect you are after ;)
I've thought of doing this with a calligraphy pen but just haven't got around to it yet.

**Comment by ChuangLee** [comment]
sorry for ambiguity example, this should explain my point ;[http://www.yac8.com/upFiles/2013/2013112360454925.jpg](http://www.yac8.com/upFiles/2013/2013112360454925.jpg)
I mean , is it possible control thickness of stroke by change the value of z axis autonomously?

**Comment by boy1dr** [comment]
yeah that would be harder. the code would need to calculate the z moves but only for the bits you wanted, that would be hard to describe in these font files. you could fork this project and have a crack at it.

**Comment by dosmanski5** [comment]
Can you use a Tevo Tarantula 3D Printer Kit 2? I have very little experience with 3D printers and I need it to run your code to write letters for me, do you think that it will work? Do I need to download your code into the 3D printer software or how does that work?

**Comment by boy1dr** [comment]
3D Writer will work with any GCODE printer. I'm not familiar with the Tevo Tarantula but if you look at the files your slicer makes and they end with .gcode or .g then chances are it will work fine.

So once you write you text in 3D Writer and click the "Generate GCode button" you will have a gcode file much the same as when you slice a model.
You just need to load that gcode file in to your printer and start the job.

First time you run it, don't worry about attaching a pen and keep your finger on the power button so if it does something unexpected you can shut it off quickly.
The only bad thing that might happen is the extruder nozzle might get too close to your build platform.
