### ISSUE TITLE
Font Editor?

### ISSUE THREAD

**Issue by pignoodle** [boy1dr/3DWriter#5]
Any updates on the progress of the font editor? It'd be really neat if you were able to create your own font from your personal hand writing. How exactly are the fonts stored anyway?

**Comment by boy1dr** [comment]
I haven't had much time to work on this project but i feel it might be time to do a bit on it soon.
The fonts are stored as coordinate pairs, a series of strokes make a character.

I think it would be rather time consuming to create a font from scratch but i guess if i provide a way to add a bitmap background in the font editor you could trace over each character and build up a custom set.
