### ISSUE TITLE
Modify text input window

### ISSUE THREAD

**Issue by vaGpl** [boy1dr/3DWriter#6]
Is it possible to modify the program to be able to enter text in columns? Each column would have its coordinates as well as offset. A good idea would be the ability to format text (align left, right, center, justify, etc.).
Currently I am entering text, setting coordinates, generating gcode, entering new text again with the appropriate offset, generating new gcode, I manually link the two codes together. It is a bit of a nuisance.

**Comment by boy1dr** [comment]
it would be possible. the current code only handles 1 process, i didn't really plan for adding multiple processes so it would require a big restructure of the program.
I'll keep it mind though as i too would like to see some of these features in there.
