### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by f-breidenstein** [boy1dr/3DWriter#7]
Hi,

the README.md is missing a chapter about "Installation" or "How to get started". I assume this is a VisualStudio project, but I have never used it and as far as I know VS is a Windows-Only software. Is there a way to get 3DWriter running without VS?

Best,
Felix

**Comment by boy1dr** [comment]
Hi Felix

Thanks for checking out my project

It is written with Visual studio C# and the project on gjthub does contain the compiled windows executable in the bin/debug folder.

If running on linux then project mono will work just fine.

Feel free to check out the source code and other comments

Let me know how you go :)


Sent from my mobile thingy



From: Felix Breidenstein
Sent: Wednesday, 27 December, 11:26 pm
Subject: [boy1dr/3DWriter] Installation guide (#7)
To: boy1dr/3DWriter
Cc: Subscribed


Hi,
the README.md is missing a chapter about "Installation" or "How to get started". I assume this is a VisualStudio project, but I have never used it and as far as I know VS is a Windows-Only software. Is there a way to get 3DWriter running without VS?
Best,
Felix

**Comment by tubbers** [comment]
i am also not that savvy, and struggled to find out how to install and run. Blindly clicking got there :-)
