### ISSUE TITLE
crash when text contains more complex characters

### ISSUE THREAD

**Issue by tubbers** [boy1dr/3DWriter#8]
Great program - Kids love it. I am getting a crash however if i paste text from a website into the input box and press preview. I assume it is special characters related (like long dash - vs –). Attached are some screen shots and crash logs

Thanks

![image](https://user-images.githubusercontent.com/38203257/38776711-b081d99a-40de-11e8-9016-a6dab8d66620.png)

[crashlog.txt](https://github.com/boy1dr/3DWriter/files/1911971/crashlog.txt)
![crash](https://user-images.githubusercontent.com/38203257/38776653-c8489d94-40dd-11e8-9c64-9e6ba85b4fe6.png)

**Comment by boy1dr** [comment]
Hi, glad you like it 😊

Try to paste the text in to notepad first, then copy it from there.
Sometimes websites have some special characters that come through with it. i'll have a look at my code and see if i can filter it out though.

Cheers,
Chris.

________________________________

**Comment by tubbers** [comment]
thanks - I have tried cut /paste via notepad, and i think it is some normal characters too (not just wacky web ones). Like variants of dashes. I am in Australia, so maybe the character set of EN_AU is different?

**Comment by boy1dr** [comment]
I am also in Australia (Brisbane) so this should work just fine. Like you say, some characters are coming through that aren't anticipated which is causing a crash.
The only thing i can suggest for now is to retype the text as you see fit. i will push out an update later tonight which will filter the text for unknown characters.

Thanks for reporting the issue, it's always good to get some feedback on these things 😊


Cheers,
Chris.

________________________________

**Comment by tubbers** [comment]
No rush. But coding is better than MKR on TV!

Our testing has been on an Anycubic i3 mega (i3 clone) with a ball point pen cable tied to the print head. Works great. I like the way you can set the lower pen level to adjust for the paper or material, and the fact that we can have the pen below the nozzle to leave it on between plots

**Comment by boy1dr** [comment]
Fixed and uploaded :)

They offending lines where placed in a try/catch so unknown characters won't cause a crash.
